<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div___3ixn</name>
   <tag></tag>
   <elementGuidId>878b0089-fcc9-42a9-85de-b62e6ed1bafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._3ixn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dacde98a-6f9d-425e-b220-1e85be8da386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3ixn</value>
      <webElementGuid>8c8112d5-f645-4f6c-aca1-9121cfe2190d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facebook&quot;)/body[@class=&quot;hideBanner _-kb _605a c_2l4os50i3 chrome webkit win x1-5 Locale_en_US cores-gte4 _19_u hasAXNavMenubar&quot;]/div[@class=&quot;_10 uiLayer _4-hy _3qw&quot;]/div[@class=&quot;_3ixn&quot;]</value>
      <webElementGuid>1e4c82d7-de3b-4fda-8384-f88fead11023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>762eb35f-2373-43af-9e09-f20182d836e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3ixn</value>
      <webElementGuid>91892633-f9a2-4d69-9068-1d6d3d0a4975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;facebook&quot;)/body[@class=&quot;hideBanner _-kb _605a c_2l4os50i3 chrome webkit win x1-5 Locale_en_US cores-gte4 _19_u hasAXNavMenubar&quot;]/div[@class=&quot;_10 uiLayer _4-hy _3qw&quot;]/div[@class=&quot;_3ixn&quot;]</value>
      <webElementGuid>ab53e546-d57b-4483-8542-602520485c66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='facebook']/body/div[4]/div</value>
      <webElementGuid>34c9a938-fb58-461a-915a-e748eccd17eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>0d38179d-c8e9-455a-b089-824a73a69deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
